quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = jboss
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/eletronic-laboratory-notebook

quarkus.hibernate-orm.database.generation = drop-and-create

quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%r %s

quarkus.mailer.mock=true
