quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = jboss
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/eletronic-laboratory-notebook

quarkus.hibernate-orm.database.generation = update
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%r %s

quarkus.mailer.mock=true

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,PUT,POST,PATCH
quarkus.hibernate-orm.log.sql=false